CREATE TABLE CONSULTA
(
	ID_Consulta INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NomeCompleto VARCHAR(50) NOT NULL, 	
 	DataNascimento DATE NOT NULL ,
	InicioConsulta DATETIME NOT NULL,
	FimConsulta DATETIME NOT NULL,
	Texto VARCHAR(300) NULL
);